#!/bin/bash
image_name="tbrixen/cryptopals"
script=$1
if [[ -z $(docker images -q $image_name) ]]; then
  docker build -t $image_name .
fi
docker run -it --rm -v $(pwd):/usr/src/cryptopals $image_name python3 $script
